---
output:
  pdf_document: default
  html_document: default
---
## Figure 1 Tables

``` yaml
---
title: "NHANES Data Exploration"
output: html_document
---
```

### Filtering Demographic Data

#### Individuals included in all surveys

```{r setup, include=FALSE}
# Load DT globally and set chunk options
library(DT)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load-and-prepare-data}
# Load libraries
library(tidyverse)
library(haven)
library(stringr)
library(purrr)
library(DT)

# read in the data (update the file paths if needed)
DI_data1 <- read_xpt("Data/DietaryInterview/2007-2008/DR1IFF_Edietary-interview-1-07-08.xpt")
demoData <- read_xpt("Data/DemographicData/DEMO_E.xpt")

partIDs <- unique(DI_data1$SEQN)

POP_files <- "Data/LaboratoryData"
POP_subdir <- list.dirs(POP_files, full.names = TRUE)
POP_subdir <- POP_subdir[-1] #removes parent directory

matching_file <- list()

for (subdir in POP_subdir) {
  file_list <- list.files(subdir, full.names = TRUE, pattern = "\\.xpt$")
  year_files <- file_list[str_detect(file_list, "2007")]
  
  if (length(year_files) > 0){
    matching_file[[subdir]] <- year_files
  }
}

matching_file <- unlist(matching_file, use.names = FALSE)

# read each file into a list
data <- map(matching_file, read_xpt)
names(data) <- basename(matching_file)

# unique SEQNs from all laboratory files
new_seqn_data <- data %>%
  map(~ pull(.x, SEQN)) %>%
  unlist() %>%
  unique()

# include only participants with laboratory (POP) data
filtered_demoData <- demoData %>% filter(SEQN %in% new_seqn_data)

final_demoData <- filtered_demoData %>% filter(SEQN %in% DI_data1$SEQN)


```

### Demographic Data Analysis

```{r demographic-summary, echo=TRUE}
library(dplyr)
library(knitr)
library(kableExtra)

#----SEX-----

sex_summary <- final_demoData %>%
  mutate(Sex = case_when(
    RIAGENDR == 1 ~ "Male",
    RIAGENDR == 2 ~ "Female",
    TRUE          ~ "Other / Unknown"
  )) %>%
  count(Sex) %>%
  mutate(percent = round(n / sum(n) * 100, 1), 
    N_val = paste0(n, " (", percent, "%)")) %>%
  select(Sex, N_val)

sex_block <- bind_rows(
  tibble(Sex = "Sex", N_val = NA_character_),
  sex_summary
) %>% rename(Table = Sex, N = N_val)

# ----RACE/ETHNICITY----

race_summary <- final_demoData %>%
  mutate(RaceEth = case_when(
    RIDRETH1 == 1 ~ "Mexican American",
    RIDRETH1 == 2 ~ "Other Hispanic",
    RIDRETH1 == 3 ~ "Non-Hispanic White",
    RIDRETH1 == 4 ~ "Non-Hispanic Black",
    RIDRETH1 == 5 ~ "Other Race/Multiracial",
    TRUE          ~ "Unknown"
  )) %>%
  count(RaceEth) %>%
  mutate(percent = round(n / sum(n) * 100, 1),
         N_val = paste0(n, " (", percent, "%)")) %>%
  select(RaceEth, N_val)

race_block <- bind_rows(
  tibble(RaceEth = "Race/Ethnicity", N_val = NA_character_),
  race_summary
) %>% rename(Table = RaceEth, N = N_val)

# ----HOUSEHOLD INCOME----

income_summary <- final_demoData %>%
  filter(INDFMIN2 %in% c(1,2,3,4,5,6,7,8,9,10,14,15)) %>%
  mutate(IncomeGroup = case_when(
    INDFMIN2 %in% c(1,2,3,4) ~ "$ 0 - $20,000",
    INDFMIN2 %in% c(5,6) ~ "$20,000 - $35,000",
    INDFMIN2 %in% c(7,8,9,10) ~ "$35,000 to $75,000",
    INDFMIN2 %in% c(14,15) ~ "$75,000+",
    TRUE ~ NA_character_
  )) %>%
  count(IncomeGroup) %>%
  mutate(percent = round(n / sum(n) * 100, 1),
         N_val = paste0(n, " (", percent, "%)")) %>%
  select(IncomeGroup, N_val)

income_block <- bind_rows(
  tibble(IncomeGroup = "Household Income", N_val = NA_character_),
  income_summary
) %>% rename(Table = IncomeGroup, N = N_val)

# ----FAMILY INCOME TO POVERTY RATIO----
pir_summary <- final_demoData %>%
  filter(!is.na(INDFMPIR)) %>%
  mutate(INDFMPIR_group = cut(INDFMPIR,
                              breaks = c(0, 1, 2, 3, 4, 5.01),
                              labels = c("<1.0", "1.0 - 1.99", "2.0 - 2.99", "3.0 - 3.99", "4.0 - 5.0+"),
                              right = FALSE)) %>%
  count(INDFMPIR_group) %>%
  mutate(percent = round(n / sum(n) * 100, 1),
         N_val = paste0(n, " (", percent, "%)")) %>%
  select(INDFMPIR_group, N_val)

pir_block <- bind_rows(
  tibble(INDFMPIR_group = "Ratio of Family Income to Poverty", N_val = NA_character_),
  pir_summary
) %>% rename(Table = INDFMPIR_group, N = N_val)

# ----COMBINE-----

final_summary <- bind_rows(
  sex_block,
  race_block,
  income_block,
  pir_block
) %>%
  select(Table, N) %>% # 2 columns
  mutate(N = if_else(is.na(N), "", N)) #remove NA values in N with empty string

# determine header row indices
n_sex <- nrow(sex_block)
n_race <- nrow(race_block)
n_income <- nrow(income_block)
n_pir <- nrow(pir_block)
header_rows <- c(1, n_sex + 1, n_sex + n_race + 1, n_sex + n_race + n_income + 1)

# ----POLISHED TABLE----
kbl <- kable(
  final_summary,
  col.names = c("Table", "N"),
  caption = "Demographic Summary"
) %>%
  kable_styling(
    bootstrap_options = c("hover", "condensed"),
    full_width = TRUE
  )

# bold header rows
for (row in header_rows) {
  kbl <- row_spec(kbl, row, bold = TRUE)
}

kbl
```
