##(BFRs) Brominated Flame Retardants
```{r}
#install tidyverse
#install haven

library(tidyverse)
library(haven)
setwd("~/nhanes-metabolic-risk")#I think this should make it work for anyone who has the repository as long as they put it in their home directory

#Let's read in the data

#let's check that all the ones from the same folder can be combined first
file.access("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_E_Brominated_Flame_Retardants_2007-2008.xpt",4)#checks if the file is accessible. If it returns 0, r can access it

BFR78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_E_Brominated_Flame_Retardants_2007-2008.xpt")
BFR78 = as_tibble(BFR78) %>% mutate(SAMPLEID = paste0(SAMPLEID,"E")) %>% mutate(YEAR = '2007-2008') %>% rename(RIDRETH3 = ETHNICTY)

BFR910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_F_Brominated_Flame_Retardants_2009-2010.xpt")
BFR910 = as_tibble(BFR910) %>% mutate(SAMPLEID = paste0(SAMPLEID,"F")) %>% mutate(YEAR = '2009-2010') %>% rename(RIDRETH3 = RIDRETH1)

BFRs = bind_rows(BFR78,BFR910)

BFR1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_G_Brominated_Flame_Retardants_2011-2012.xpt")
BFR1112 = as_tibble(BFR1112) %>% mutate(SAMPLEID = paste0(SAMPLEID,"G")) %>% mutate(YEAR = '2011-2012')

BFRs = bind_rows(BFRs, BFR1112)

BFR1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_H_Brominated_Flame_Retardants_2013-2014.xpt")
BFR1314 = as_tibble(BFR1314) %>% mutate(SAMPLEID = paste0(SAMPLEID,"H")) %>% mutate(YEAR = '2013-2014')

BFRs = bind_rows(BFRs, BFR1314)

BFR1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/brominated-flame-retardant/BFRPOL_I_Brominated_Flame_Retardants_2015-2016.xpt")
BFR1516 = as_tibble(BFR1516) %>% mutate(SAMPLEID = paste0(SAMPLEID,"I")) %>% mutate(YEAR = '2015-2016')

BFRs = bind_rows(BFRs, BFR1516)

#Ok, now the data is all in one table. But, I think we want to visualize all the POPs in one figure, or at least have one figure per year if there are too many. This means I need to combine them together to get the total levels of BFRs. I figure I can just add them, but I need to make them be in the same units

```
##Cadmium, Lead, and Manganese
```{r}
PBCD78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_E_Cadmium_Lead_and_Total_Mercury_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

PBCD910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_F_Cadmium_Lead_and_Total_Mercury_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

PBCDs = bind_rows(PBCD78, PBCD910)

PBCD1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_G_Cadmium_Lead_Total Mercury_Selenium_and_Manganese_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

PBCDs = bind_rows(PBCDs, PBCD1112)

PBCD1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_H_Cadmium_Lead_Total Mercury_Selenium_and_Manganese_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

PBCDs = bind_rows(PBCDs, PBCD1314)

PBCD1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_I_Cadmium_Lead_Total Mercury_Selenium_and_Manganese_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

PBCDs = bind_rows(PBCDs, PBCD1516)

PBCD1718 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/Cadmium-Lead-and-manganese/PBCD_J_Cadmium_Lead_Total Mercury_Selenium_and_Manganese_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

PBCDs = bind_rows(PBCDs, PBCD1718)
#this one has some gaps, and one column that seems to be unique to one table? I'm not sure which one it comes from, but it's called WTSH2YR
```
##Evironmental Phenols
```{r}
EPH78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/environmental-phenols/EPH_E_Environmental_Phenols_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

EPH910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/environmental-phenols/EPH_F_Environmental_Phenols_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

EPH = bind_rows(EPH78, EPH910)

EPH1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/environmental-phenols/EPH_G__Environmental_Phenols_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

EPH = bind_rows(EPH, EPH1112)
#same as the last time
```
##Flame retardants
```{r}
FR1718 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/flame-retardants/FR_J_Flame_Retardants_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

FR1718s = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/flame-retardants/SSFR_J_Flame_Retardants_surplus_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

FR1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/flame-retardants/SSFR_G_Flame_Retardants_surplus_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

FR1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/flame-retardants/SSFR_I_Flame_Retardants_surplus_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

FR = bind_rows(FR1718,FR1718s)

FR = bind_rows(FR,FR1112)

FR = bind_rows(FR, FR1516)

#These ones match up very poorly
```
##Metals
```{r}
M78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UHM_E_Metals_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

M910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UHM_F_Metals_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

Ms = bind_rows(M78, M910)

M1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UHM_G_Metals_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

Ms = bind_rows(Ms, M1112)

M1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UM_H_Metals_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

Ms = bind_rows(Ms, M1314)

M1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UM_I_Metals_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

Ms = bind_rows(Ms, M1516)

M1718 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/metals/UM_J_Metals_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

Ms = bind_rows(Ms, M1718)
#I think this one has some columns that are named differently. Need to check
```
##Organophosphate Insecticides
```{r}
OI78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/organophosphate-insecticides/OPD_E_Organophosphate_Insecticides_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

OI1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/organophosphate-insecticides/OPD_G_Organophosphate_Insecticides_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

OI = bind_rows(OI78, OI1112)#these match up well

OI1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/organophosphate-insecticides/OPD_I_Organophosphate_Insecticides_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

OI = bind_rows(OI, OI1516)#so do these

OI1718 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/organophosphate-insecticides/OPD_J_Organophosphate_Insecticides_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

OI = bind_rows(OI, OI1718)#and these
```
##Pesticides
```{r}
#Environmental
PP78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PP_E_Pesticides_Evironmental_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

PP910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PP_F_Pesticides_Evironmental_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

PPs = bind_rows(PP78, PP910)#these match up exactly

PP1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PP_G_Pesticides_Evironmental_2011-2012.xpt") %>% mutate(YEAR = '2009-2010')

PPs = bind_rows(PPs, PP1112)#these don't match up

#Organochlorine
PO78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PSTPOL_E_Organochlorine_Pesticides_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

PO910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PSTPOL_F_Organochlorine_Pesticides_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

POs = bind_rows(PO78, PO910)# these have a 1 row that doesn't match

PO1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PSTPOL_G_Organochlorine_Pesticides_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

POs = bind_rows(POs, PO1112)# this has at least 1 row that doesn't match

PO1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PSTPOL_H_Organochlorine_Pesticides_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

POs = bind_rows(POs, PO1314)# this has another one

PO1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pesticides/PSTPOL_I_Organochlorine_Pesticides_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

POs = bind_rows(POs, PO1516)# and another

#there's a few other files in this section
```
##Polyfluoroalkyl Chemicals
```{r}
PFC78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/polyfluoroalkyl-chemicals/PFC_E_Polyfluoroalkyl_Chemicals_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

PFC910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/polyfluoroalkyl-chemicals/PFC_F_Polyfluoroalkyl_Chemicals_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

PFCs = bind_rows(PFC78, PFC910)#these match exactly

PFC1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/polyfluoroalkyl-chemicals/PFC_G_Polyfluoroalkyl_Chemicals_2011-2012.xpt") %>% mutate(YEAR = '2010-2012')

PFCs = bind_rows(PFCs, PFC1112)#this has 1 mismatch

PFC1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/polyfluoroalkyl-chemicals/PFAS_H_Polyfluoroalkyl_Chemicals_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

PFCs = bind_rows(PFCs, PFC1314)#so does this
```
##Pyrethroids, Herbicides, and OP Metabolites
```{r}
PHOPM78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pyrethroids-herbicides-and-OP-metabolites/UPHOPM_E_Pyrethroids_Herbicides_and_OPs_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

PHOPM910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pyrethroids-herbicides-and-OP-metabolites/UPHOPM_F_Pyrethroids_Herbicides_and_OPs_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

PHOPMs = bind_rows(PHOPM78, PHOPM910)#these match well

PHOPM1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pyrethroids-herbicides-and-OP-metabolites/UPHOPM_G_Pyrethroids_Herbicides_and_OPs_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

PHOPMs = bind_rows(PHOPMs, PHOPM1112) #this fits pretty well, though 1112 is missing a lot of columns. But all the ones it has matches

PHOPM1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pyrethroids-herbicides-and-OP-metabolites/UPHOPM_H_Pyrethroids_Herbicides_and_OPs_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

PHOPMs = bind_rows(PHOPMs, PHOPM1314)#this fits well too, though it is also missing columns

PHOPM1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/pyrethroids-herbicides-and-OP-metabolites/UPHOPM_I_Pyrethroids_Herbicides_and_OPs_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

PHOPMs = bind_rows(PHOPMs, PHOPM1516)#this one has 1 mismatch
```
##Standard Biochemistry Profile
```{r}
BIOPRO78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_E_Standard_Biochemistry_Profile_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

BIOPRO910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_F_Standard_Biochemistry_Profile_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

BIOPROs = bind_rows(BIOPRO78, BIOPRO910)#these match well

BIOPRO1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_G_Standard_Biochemistry_Profile_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

BIOPROs = bind_rows(BIOPROs, BIOPRO1112)#these match up well

BIOPRO1314 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_H_Standard_Biochemistry_Profile_2013-2014.xpt") %>% mutate(YEAR = '2013-2014')

BIOPROs = bind_rows(BIOPROs, BIOPRO1314)#this matches up well

BIOPRO1516 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_I_Standard_Biochemistry_Profile_2015-2016.xpt") %>% mutate(YEAR = '2015-2016')

BIOPROs = bind_rows(BIOPROs, BIOPRO1516)#this too

BIOPRO1718 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/standard-biochemistry-profile/BIOPRO_J_Standard_Biochemistry_Profile_2017-2018.xpt") %>% mutate(YEAR = '2017-2018')

BIOPROs = bind_rows(BIOPROs, BIOPRO1718)#this one adds a few columns, but it looks like most of them are in common

```
##Thyroid Profile
```{r}
THYROD78 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/thyroid-profile/THYROD_E_Thyroid_Profile_2007-2008.xpt") %>% mutate(YEAR = '2007-2008')

THYROD910 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/thyroid-profile/THYROD_F_Thyroid_Profile_2009-2010.xpt") %>% mutate(YEAR = '2009-2010')

THYRODs = bind_rows(THYROD78, THYROD910) #these match up well

THYROD1112 = read_xpt("~/nhanes-metabolic-risk/LaboratoryData/thyroid-profile/THYROD_G_Thyroid_Profile_2011-2012.xpt") %>% mutate(YEAR = '2011-2012')

THYRODs = bind_rows(THYRODs, THYROD1112)#so does this one
```

